/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GWNU_daycalculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

}

public static void main(String[] args) {
    DayCalculator dayCalculator = new DayCalculator();
    dayCalculator.setDate(2022, 6, 3);
    System.out.println(dayCalculator.getDayofWeek());
}