/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GWNU_daycalculator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("test3");
        System.out.println("test3");
    }
}
